- hosts: all
  gather_facts: false
  tasks:
    - name: Accept new ssh fingerprints
      shell: ssh-keyscan {{ inventory_hostname }} >> ~/.ssh/known_hosts
      delegate_to: localhost

- hosts: all
  remote_user: "{{ vm_user }}"
  gather_facts: false
  tasks:
    - name: Wait for ssh to be up on the nodes
      ansible.builtin.wait_for_connection:

    - name: ping
      ping:

- hosts: all[0]
  remote_user: "{{ vm_user }}"
  gather_facts: false
  tasks:
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      community.crypto.openssh_keypair:
        path: /home/{{ vm_user }}/.ssh/id_rsa

    - name: Get pub key for the first node
      ansible.builtin.fetch:
        src: /home/{{ vm_user }}/.ssh/id_rsa.pub
        dest: bench_id_rsa.pub
        flat: true

- hosts: all
  remote_user: "{{ vm_user }}"
  gather_facts: false
  tasks:
    - name: Set authorized pub key
      authorized_key:
        state: present
        user: "{{ vm_user }}"
        key: "{{ lookup('file', 'bench_id_rsa.pub') }}"

    - name: Copy lskv repo over
      ansible.posix.synchronize:
        src: "{{ playbook_dir }}/../"
        dest: /tmp/lskv

    - name: Install apt packages
      ansible.builtin.apt:
        name:
          - make
          - python3.8
          - python3.8-venv
        update_cache: true
      become: true

    - name: Install openenclave
      ansible.builtin.apt:
        deb: "{{ oe_deb }}"
        update_cache: true
      become: true

    - name: Install ccf
      ansible.builtin.apt:
        deb: "{{ ccf_deb }}"
        update_cache: true
        force: true
      become: true

    - name: Install app dev deps
      ansible.builtin.command:
        cmd: /opt/ccf_virtual/getting_started/setup_vm/run.sh /opt/ccf_virtual/getting_started/setup_vm/app-dev.yml --extra-vars "platform=virtual" --extra-vars "oe_ver='{{ oe_ver }}'" --extra-vars "oe_ver_='{{ oe_ver_ }}'"

- hosts: all[0]
  remote_user: "{{ vm_user }}"
  gather_facts: false
  tasks:
    - name: Install deps for sandbox
      ansible.builtin.pip:
        name: pip
        virtualenv: /tmp/lskv/.venv_ccf_sandbox
        virtualenv_command: python3 -m venv

    - name: Install deps for sandbox
      ansible.builtin.pip:
        name: ccf=={{ py_ccf_ver }}
        virtualenv: /tmp/lskv/.venv_ccf_sandbox
        virtualenv_command: python3 -m venv

    - name: Install deps for sandbox
      ansible.builtin.pip:
        requirements: /opt/ccf_virtual/bin/requirements.txt
        virtualenv: /tmp/lskv/.venv_ccf_sandbox
        virtualenv_command: python3 -m venv

    - name: Install deps for benchmarking
      ansible.builtin.pip:
        requirements: /tmp/lskv/requirements.txt
        virtualenv: /tmp/lskv/.venv
        virtualenv_command: python3 -m venv
