"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class KeyValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    CREATE_REVISION_FIELD_NUMBER: builtins.int
    MOD_REVISION_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    LEASE_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    """key is the key in bytes. An empty key is not allowed."""
    create_revision: builtins.int
    """create_revision is the revision of last creation on this key."""
    mod_revision: builtins.int
    """mod_revision is the revision of last modification on this key."""
    version: builtins.int
    """version is the version of the key. A deletion resets
    the version to zero and any modification of the key
    increases its version.
    """
    value: builtins.bytes
    """value is the value held by the key, in bytes."""
    lease: builtins.int
    """lease is the ID of the lease that attached to key.
    When the attached lease expires, the key will be deleted.
    If lease is 0, then no lease is attached to the key.
    """
    def __init__(
        self,
        *,
        key: builtins.bytes = ...,
        create_revision: builtins.int = ...,
        mod_revision: builtins.int = ...,
        version: builtins.int = ...,
        value: builtins.bytes = ...,
        lease: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["create_revision", b"create_revision", "key", b"key", "lease", b"lease", "mod_revision", b"mod_revision", "value", b"value", "version", b"version"]) -> None: ...

global___KeyValue = KeyValue

@typing_extensions.final
class ResponseHeader(google.protobuf.message.Message):
    """option (versionpb.etcd_version_msg) = "3.0";"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLUSTER_ID_FIELD_NUMBER: builtins.int
    MEMBER_ID_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    RAFT_TERM_FIELD_NUMBER: builtins.int
    COMMITTED_REVISION_FIELD_NUMBER: builtins.int
    COMMITTED_RAFT_TERM_FIELD_NUMBER: builtins.int
    cluster_id: builtins.int
    """cluster_id is the ID of the cluster which sent the response."""
    member_id: builtins.int
    """member_id is the ID of the member which sent the response."""
    revision: builtins.int
    """revision is the key-value store revision when the request was applied, and
    it's unset (so 0) in case of calls not interacting with key-value store.
    For watch progress responses, the header.revision indicates progress. All
    future events received in this stream are guaranteed to have a higher
    revision number than the header.revision number.
    """
    raft_term: builtins.int
    """raft_term is the raft term when the request was applied."""
    committed_revision: builtins.int
    """revision of the store that has most recently been committed (been through
    consensus).
    """
    committed_raft_term: builtins.int
    """raft term that the last committed item was committed in."""
    def __init__(
        self,
        *,
        cluster_id: builtins.int = ...,
        member_id: builtins.int = ...,
        revision: builtins.int = ...,
        raft_term: builtins.int = ...,
        committed_revision: builtins.int = ...,
        committed_raft_term: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cluster_id", b"cluster_id", "committed_raft_term", b"committed_raft_term", "committed_revision", b"committed_revision", "member_id", b"member_id", "raft_term", b"raft_term", "revision", b"revision"]) -> None: ...

global___ResponseHeader = ResponseHeader

@typing_extensions.final
class RangeRequest(google.protobuf.message.Message):
    """option (versionpb.etcd_version_msg) = "3.0";"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _SortOrder:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SortOrderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RangeRequest._SortOrder.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NONE: RangeRequest._SortOrder.ValueType  # 0
        """  option (versionpb.etcd_version_enum) = "3.0";
        default, no sorting
        """
        ASCEND: RangeRequest._SortOrder.ValueType  # 1
        """lowest target value first"""
        DESCEND: RangeRequest._SortOrder.ValueType  # 2
        """highest target value first"""

    class SortOrder(_SortOrder, metaclass=_SortOrderEnumTypeWrapper): ...
    NONE: RangeRequest.SortOrder.ValueType  # 0
    """  option (versionpb.etcd_version_enum) = "3.0";
    default, no sorting
    """
    ASCEND: RangeRequest.SortOrder.ValueType  # 1
    """lowest target value first"""
    DESCEND: RangeRequest.SortOrder.ValueType  # 2
    """highest target value first"""

    class _SortTarget:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SortTargetEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RangeRequest._SortTarget.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        KEY: RangeRequest._SortTarget.ValueType  # 0
        """  option (versionpb.etcd_version_enum) = "3.0";"""
        VERSION: RangeRequest._SortTarget.ValueType  # 1
        CREATE: RangeRequest._SortTarget.ValueType  # 2
        MOD: RangeRequest._SortTarget.ValueType  # 3
        VALUE: RangeRequest._SortTarget.ValueType  # 4

    class SortTarget(_SortTarget, metaclass=_SortTargetEnumTypeWrapper): ...
    KEY: RangeRequest.SortTarget.ValueType  # 0
    """  option (versionpb.etcd_version_enum) = "3.0";"""
    VERSION: RangeRequest.SortTarget.ValueType  # 1
    CREATE: RangeRequest.SortTarget.ValueType  # 2
    MOD: RangeRequest.SortTarget.ValueType  # 3
    VALUE: RangeRequest.SortTarget.ValueType  # 4

    KEY_FIELD_NUMBER: builtins.int
    RANGE_END_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    SORT_ORDER_FIELD_NUMBER: builtins.int
    SORT_TARGET_FIELD_NUMBER: builtins.int
    SERIALIZABLE_FIELD_NUMBER: builtins.int
    KEYS_ONLY_FIELD_NUMBER: builtins.int
    COUNT_ONLY_FIELD_NUMBER: builtins.int
    MIN_MOD_REVISION_FIELD_NUMBER: builtins.int
    MAX_MOD_REVISION_FIELD_NUMBER: builtins.int
    MIN_CREATE_REVISION_FIELD_NUMBER: builtins.int
    MAX_CREATE_REVISION_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    """key is the first key for the range. If range_end is not given, the request
    only looks up key.
    """
    range_end: builtins.bytes
    """range_end is the upper bound on the requested range [key, range_end).
    If range_end is '\\0', the range is all keys >= key.
    If range_end is key plus one (e.g., "aa"+1 == "ab", "a\\xff"+1 == "b"),
    then the range request gets all keys prefixed with key.
    If both key and range_end are '\\0', then the range request returns all
    keys.
    """
    limit: builtins.int
    """limit is a limit on the number of keys returned for the request. When limit
    is set to 0, it is treated as no limit.
    """
    revision: builtins.int
    """revision is the point-in-time of the key-value store to use for the range.
    If revision is less or equal to zero, the range is over the newest
    key-value store. If the revision has been compacted, ErrCompacted is
    returned as a response.
    """
    sort_order: global___RangeRequest.SortOrder.ValueType
    """sort_order is the order for returned sorted results."""
    sort_target: global___RangeRequest.SortTarget.ValueType
    """sort_target is the key-value field to use for sorting."""
    serializable: builtins.bool
    """serializable sets the range request to use serializable member-local reads.
    Range requests are linearizable by default; linearizable requests have
    higher latency and lower throughput than serializable requests but reflect
    the current consensus of the cluster. For better performance, in exchange
    for possible stale reads, a serializable range request is served locally
    without needing to reach consensus with other nodes in the cluster.
    """
    keys_only: builtins.bool
    """keys_only when set returns only the keys and not the values."""
    count_only: builtins.bool
    """count_only when set returns only the count of the keys in the range."""
    min_mod_revision: builtins.int
    """min_mod_revision is the lower bound for returned key mod revisions; all
    keys with lesser mod revisions will be filtered away.
    [(versionpb.etcd_version_field)="3.1"];
    """
    max_mod_revision: builtins.int
    """// max_mod_revision is the upper bound for returned key mod revisions; all
    keys with
    // greater mod revisions will be filtered away.
    [(versionpb.etcd_version_field)="3.1"];
    """
    min_create_revision: builtins.int
    """// min_create_revision is the lower bound for returned key create
    revisions; all keys with
    // lesser create revisions will be filtered away.
    [(versionpb.etcd_version_field)="3.1"];
    """
    max_create_revision: builtins.int
    """// max_create_revision is the upper bound for returned key create
    revisions; all keys with
    // greater create revisions will be filtered away.
    [(versionpb.etcd_version_field)="3.1"];
    """
    def __init__(
        self,
        *,
        key: builtins.bytes = ...,
        range_end: builtins.bytes = ...,
        limit: builtins.int = ...,
        revision: builtins.int = ...,
        sort_order: global___RangeRequest.SortOrder.ValueType = ...,
        sort_target: global___RangeRequest.SortTarget.ValueType = ...,
        serializable: builtins.bool = ...,
        keys_only: builtins.bool = ...,
        count_only: builtins.bool = ...,
        min_mod_revision: builtins.int = ...,
        max_mod_revision: builtins.int = ...,
        min_create_revision: builtins.int = ...,
        max_create_revision: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["count_only", b"count_only", "key", b"key", "keys_only", b"keys_only", "limit", b"limit", "max_create_revision", b"max_create_revision", "max_mod_revision", b"max_mod_revision", "min_create_revision", b"min_create_revision", "min_mod_revision", b"min_mod_revision", "range_end", b"range_end", "revision", b"revision", "serializable", b"serializable", "sort_order", b"sort_order", "sort_target", b"sort_target"]) -> None: ...

global___RangeRequest = RangeRequest

@typing_extensions.final
class RangeResponse(google.protobuf.message.Message):
    """option (versionpb.etcd_version_msg) = "3.0";"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    KVS_FIELD_NUMBER: builtins.int
    MORE_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___ResponseHeader: ...
    @property
    def kvs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___KeyValue]:
        """kvs is the list of key-value pairs matched by the range request.
        kvs is empty when count is requested.
        TODO: Move to new file
        """
    more: builtins.bool
    """more indicates if there are more keys to return in the requested range."""
    count: builtins.int
    """count is set to the number of keys within the range when requested."""
    def __init__(
        self,
        *,
        header: global___ResponseHeader | None = ...,
        kvs: collections.abc.Iterable[global___KeyValue] | None = ...,
        more: builtins.bool = ...,
        count: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["count", b"count", "header", b"header", "kvs", b"kvs", "more", b"more"]) -> None: ...

global___RangeResponse = RangeResponse

@typing_extensions.final
class PutRequest(google.protobuf.message.Message):
    """option (versionpb.etcd_version_msg) = "3.0";"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    LEASE_FIELD_NUMBER: builtins.int
    PREV_KV_FIELD_NUMBER: builtins.int
    IGNORE_VALUE_FIELD_NUMBER: builtins.int
    IGNORE_LEASE_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    """key is the key, in bytes, to put into the key-value store."""
    value: builtins.bytes
    """value is the value, in bytes, to associate with the key in the key-value
    store.
    """
    lease: builtins.int
    """lease is the lease ID to associate with the key in the key-value store. A
    lease value of 0 indicates no lease.
    """
    prev_kv: builtins.bool
    """If prev_kv is set, etcd gets the previous key-value pair before changing
    it. The previous key-value pair will be returned in the put response.
    [(versionpb.etcd_version_field)="3.1"];
    """
    ignore_value: builtins.bool
    """// If ignore_value is set, etcd updates the key using its current value.
    // Returns an error if the key does not exist.
    [(versionpb.etcd_version_field)="3.2"];
    """
    ignore_lease: builtins.bool
    """// If ignore_lease is set, etcd updates the key using its current lease.
    // Returns an error if the key does not exist.
    [(versionpb.etcd_version_field)="3.2"];
    """
    def __init__(
        self,
        *,
        key: builtins.bytes = ...,
        value: builtins.bytes = ...,
        lease: builtins.int = ...,
        prev_kv: builtins.bool = ...,
        ignore_value: builtins.bool = ...,
        ignore_lease: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ignore_lease", b"ignore_lease", "ignore_value", b"ignore_value", "key", b"key", "lease", b"lease", "prev_kv", b"prev_kv", "value", b"value"]) -> None: ...

global___PutRequest = PutRequest

@typing_extensions.final
class PutResponse(google.protobuf.message.Message):
    """option (versionpb.etcd_version_msg) = "3.0";"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    PREV_KV_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___ResponseHeader: ...
    @property
    def prev_kv(self) -> global___KeyValue:
        """if prev_kv is set in the request, the previous key-value pair will be
        returned.
        [(versionpb.etcd_version_field)="3.1"]; // TODO: Move to new file
        """
    def __init__(
        self,
        *,
        header: global___ResponseHeader | None = ...,
        prev_kv: global___KeyValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header", "prev_kv", b"prev_kv"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["header", b"header", "prev_kv", b"prev_kv"]) -> None: ...

global___PutResponse = PutResponse

@typing_extensions.final
class DeleteRangeRequest(google.protobuf.message.Message):
    """option (versionpb.etcd_version_msg) = "3.0";"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    RANGE_END_FIELD_NUMBER: builtins.int
    PREV_KV_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    """key is the first key to delete in the range."""
    range_end: builtins.bytes
    """range_end is the key following the last key to delete for the range [key,
    range_end). If range_end is not given, the range is defined to contain only
    the key argument. If range_end is one bit larger than the given key, then
    the range is all the keys with the prefix (the given key). If range_end is
    '\\0', the range is all keys greater than or equal to the key argument.
    """
    prev_kv: builtins.bool
    """If prev_kv is set, etcd gets the previous key-value pairs before deleting
    it. The previous key-value pairs will be returned in the delete response.
    [(versionpb.etcd_version_field)="3.1"];
    """
    def __init__(
        self,
        *,
        key: builtins.bytes = ...,
        range_end: builtins.bytes = ...,
        prev_kv: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "prev_kv", b"prev_kv", "range_end", b"range_end"]) -> None: ...

global___DeleteRangeRequest = DeleteRangeRequest

@typing_extensions.final
class DeleteRangeResponse(google.protobuf.message.Message):
    """option (versionpb.etcd_version_msg) = "3.0";"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    DELETED_FIELD_NUMBER: builtins.int
    PREV_KVS_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___ResponseHeader: ...
    deleted: builtins.int
    """deleted is the number of keys deleted by the delete range request."""
    @property
    def prev_kvs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___KeyValue]:
        """if prev_kv is set in the request, the previous key-value pairs will be
        returned.
        [(versionpb.etcd_version_field)="3.1"];
        """
    def __init__(
        self,
        *,
        header: global___ResponseHeader | None = ...,
        deleted: builtins.int = ...,
        prev_kvs: collections.abc.Iterable[global___KeyValue] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["deleted", b"deleted", "header", b"header", "prev_kvs", b"prev_kvs"]) -> None: ...

global___DeleteRangeResponse = DeleteRangeResponse

@typing_extensions.final
class RequestOp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_RANGE_FIELD_NUMBER: builtins.int
    REQUEST_PUT_FIELD_NUMBER: builtins.int
    REQUEST_DELETE_RANGE_FIELD_NUMBER: builtins.int
    REQUEST_TXN_FIELD_NUMBER: builtins.int
    @property
    def request_range(self) -> global___RangeRequest: ...
    @property
    def request_put(self) -> global___PutRequest: ...
    @property
    def request_delete_range(self) -> global___DeleteRangeRequest: ...
    @property
    def request_txn(self) -> global___TxnRequest: ...
    def __init__(
        self,
        *,
        request_range: global___RangeRequest | None = ...,
        request_put: global___PutRequest | None = ...,
        request_delete_range: global___DeleteRangeRequest | None = ...,
        request_txn: global___TxnRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["request", b"request", "request_delete_range", b"request_delete_range", "request_put", b"request_put", "request_range", b"request_range", "request_txn", b"request_txn"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["request", b"request", "request_delete_range", b"request_delete_range", "request_put", b"request_put", "request_range", b"request_range", "request_txn", b"request_txn"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["request", b"request"]) -> typing_extensions.Literal["request_range", "request_put", "request_delete_range", "request_txn"] | None: ...

global___RequestOp = RequestOp

@typing_extensions.final
class ResponseOp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESPONSE_RANGE_FIELD_NUMBER: builtins.int
    RESPONSE_PUT_FIELD_NUMBER: builtins.int
    RESPONSE_DELETE_RANGE_FIELD_NUMBER: builtins.int
    RESPONSE_TXN_FIELD_NUMBER: builtins.int
    @property
    def response_range(self) -> global___RangeResponse: ...
    @property
    def response_put(self) -> global___PutResponse: ...
    @property
    def response_delete_range(self) -> global___DeleteRangeResponse: ...
    @property
    def response_txn(self) -> global___TxnResponse: ...
    def __init__(
        self,
        *,
        response_range: global___RangeResponse | None = ...,
        response_put: global___PutResponse | None = ...,
        response_delete_range: global___DeleteRangeResponse | None = ...,
        response_txn: global___TxnResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response", b"response", "response_delete_range", b"response_delete_range", "response_put", b"response_put", "response_range", b"response_range", "response_txn", b"response_txn"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["response", b"response", "response_delete_range", b"response_delete_range", "response_put", b"response_put", "response_range", b"response_range", "response_txn", b"response_txn"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["response", b"response"]) -> typing_extensions.Literal["response_range", "response_put", "response_delete_range", "response_txn"] | None: ...

global___ResponseOp = ResponseOp

@typing_extensions.final
class Compare(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _CompareResult:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _CompareResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Compare._CompareResult.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        EQUAL: Compare._CompareResult.ValueType  # 0
        GREATER: Compare._CompareResult.ValueType  # 1
        LESS: Compare._CompareResult.ValueType  # 2
        NOT_EQUAL: Compare._CompareResult.ValueType  # 3

    class CompareResult(_CompareResult, metaclass=_CompareResultEnumTypeWrapper): ...
    EQUAL: Compare.CompareResult.ValueType  # 0
    GREATER: Compare.CompareResult.ValueType  # 1
    LESS: Compare.CompareResult.ValueType  # 2
    NOT_EQUAL: Compare.CompareResult.ValueType  # 3

    class _CompareTarget:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _CompareTargetEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Compare._CompareTarget.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        VERSION: Compare._CompareTarget.ValueType  # 0
        CREATE: Compare._CompareTarget.ValueType  # 1
        MOD: Compare._CompareTarget.ValueType  # 2
        VALUE: Compare._CompareTarget.ValueType  # 3
        LEASE: Compare._CompareTarget.ValueType  # 4

    class CompareTarget(_CompareTarget, metaclass=_CompareTargetEnumTypeWrapper): ...
    VERSION: Compare.CompareTarget.ValueType  # 0
    CREATE: Compare.CompareTarget.ValueType  # 1
    MOD: Compare.CompareTarget.ValueType  # 2
    VALUE: Compare.CompareTarget.ValueType  # 3
    LEASE: Compare.CompareTarget.ValueType  # 4

    RESULT_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    CREATE_REVISION_FIELD_NUMBER: builtins.int
    MOD_REVISION_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    LEASE_FIELD_NUMBER: builtins.int
    RANGE_END_FIELD_NUMBER: builtins.int
    result: global___Compare.CompareResult.ValueType
    """result is logical comparison operation for this comparison."""
    target: global___Compare.CompareTarget.ValueType
    """target is the key-value field to inspect for the comparison."""
    key: builtins.bytes
    """key is the subject key for the comparison operation."""
    version: builtins.int
    """version is the version of the given key"""
    create_revision: builtins.int
    """create_revision is the creation revision of the given key"""
    mod_revision: builtins.int
    """mod_revision is the last modified revision of the given key."""
    value: builtins.bytes
    """value is the value of the given key, in bytes."""
    lease: builtins.int
    """lease is the lease id of the given key.
    leave room for more target_union field tags, jump to 64
    """
    range_end: builtins.bytes
    """range_end compares the given target to all keys in the range [key,
    range_end). See RangeRequest for more details on key ranges.
    TODO: fill out with most of the rest of RangeRequest fields when needed.
    """
    def __init__(
        self,
        *,
        result: global___Compare.CompareResult.ValueType = ...,
        target: global___Compare.CompareTarget.ValueType = ...,
        key: builtins.bytes = ...,
        version: builtins.int = ...,
        create_revision: builtins.int = ...,
        mod_revision: builtins.int = ...,
        value: builtins.bytes = ...,
        lease: builtins.int = ...,
        range_end: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_revision", b"create_revision", "lease", b"lease", "mod_revision", b"mod_revision", "target_union", b"target_union", "value", b"value", "version", b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["create_revision", b"create_revision", "key", b"key", "lease", b"lease", "mod_revision", b"mod_revision", "range_end", b"range_end", "result", b"result", "target", b"target", "target_union", b"target_union", "value", b"value", "version", b"version"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["target_union", b"target_union"]) -> typing_extensions.Literal["version", "create_revision", "mod_revision", "value", "lease"] | None: ...

global___Compare = Compare

@typing_extensions.final
class TxnRequest(google.protobuf.message.Message):
    """From google paxosdb paper:
    Our implementation hinges around a powerful primitive which we call MultiOp.
    All other database operations except for iteration are implemented as a
    single call to MultiOp. A MultiOp is applied atomically and consists of three
    components:
    1. A list of tests called guard. Each test in guard checks a single entry in
    the database. It may check for the absence or presence of a value, or compare
    with a given value. Two different tests in the guard may apply to the same or
    different entries in the database. All tests in the guard are applied and
    MultiOp returns the results. If all tests are true, MultiOp executes t op
    (see item 2 below), otherwise it executes f op (see item 3 below).
    2. A list of database operations called t op. Each operation in the list is
    either an insert, delete, or lookup operation, and applies to a single
    database entry. Two different operations in the list may apply to the same or
    different entries in the database. These operations are executed if guard
    evaluates to true.
    3. A list of database operations called f op. Like t op, but executed if
    guard evaluates to false.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COMPARE_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    FAILURE_FIELD_NUMBER: builtins.int
    @property
    def compare(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Compare]:
        """compare is a list of predicates representing a conjunction of terms.
        If the comparisons succeed, then the success requests will be processed in
        order, and the response will contain their respective responses in order.
        If the comparisons fail, then the failure requests will be processed in
        order, and the response will contain their respective responses in order.
        """
    @property
    def success(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RequestOp]:
        """success is a list of requests which will be applied when compare evaluates
        to true.
        """
    @property
    def failure(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RequestOp]:
        """failure is a list of requests which will be applied when compare evaluates
        to false.
        """
    def __init__(
        self,
        *,
        compare: collections.abc.Iterable[global___Compare] | None = ...,
        success: collections.abc.Iterable[global___RequestOp] | None = ...,
        failure: collections.abc.Iterable[global___RequestOp] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["compare", b"compare", "failure", b"failure", "success", b"success"]) -> None: ...

global___TxnRequest = TxnRequest

@typing_extensions.final
class TxnResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    SUCCEEDED_FIELD_NUMBER: builtins.int
    RESPONSES_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___ResponseHeader: ...
    succeeded: builtins.bool
    """succeeded is set to true if the compare evaluated to true or false
    otherwise.
    """
    @property
    def responses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResponseOp]:
        """responses is a list of responses corresponding to the results from applying
        success if succeeded is true or failure if succeeded is false.
        """
    def __init__(
        self,
        *,
        header: global___ResponseHeader | None = ...,
        succeeded: builtins.bool = ...,
        responses: collections.abc.Iterable[global___ResponseOp] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["header", b"header", "responses", b"responses", "succeeded", b"succeeded"]) -> None: ...

global___TxnResponse = TxnResponse

@typing_extensions.final
class CompactionRequest(google.protobuf.message.Message):
    """CompactionRequest compacts the key-value store up to a given revision. All
    superseded keys with a revision less than the compaction revision will be
    removed.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REVISION_FIELD_NUMBER: builtins.int
    PHYSICAL_FIELD_NUMBER: builtins.int
    revision: builtins.int
    """revision is the key-value store revision for the compaction operation."""
    physical: builtins.bool
    """physical is set so the RPC will wait until the compaction is physically
    applied to the local database such that compacted entries are totally
    removed from the backend database.
    """
    def __init__(
        self,
        *,
        revision: builtins.int = ...,
        physical: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["physical", b"physical", "revision", b"revision"]) -> None: ...

global___CompactionRequest = CompactionRequest

@typing_extensions.final
class CompactionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___ResponseHeader: ...
    def __init__(
        self,
        *,
        header: global___ResponseHeader | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["header", b"header"]) -> None: ...

global___CompactionResponse = CompactionResponse

@typing_extensions.final
class LeaseGrantRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TTL_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    TTL: builtins.int
    """TTL is the advisory time-to-live in seconds. Expired lease will return -1."""
    ID: builtins.int
    """ID is the requested ID for the lease. If ID is set to 0, the lessor chooses
    an ID.
    """
    def __init__(
        self,
        *,
        TTL: builtins.int = ...,
        ID: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ID", b"ID", "TTL", b"TTL"]) -> None: ...

global___LeaseGrantRequest = LeaseGrantRequest

@typing_extensions.final
class LeaseGrantResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    TTL_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___ResponseHeader: ...
    ID: builtins.int
    """ID is the lease ID for the granted lease."""
    TTL: builtins.int
    """TTL is the server chosen lease time-to-live in seconds."""
    error: builtins.str
    def __init__(
        self,
        *,
        header: global___ResponseHeader | None = ...,
        ID: builtins.int = ...,
        TTL: builtins.int = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ID", b"ID", "TTL", b"TTL", "error", b"error", "header", b"header"]) -> None: ...

global___LeaseGrantResponse = LeaseGrantResponse

@typing_extensions.final
class LeaseRevokeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    ID: builtins.int
    """ID is the lease ID to revoke. When the ID is revoked, all associated keys
    will be deleted.
    """
    def __init__(
        self,
        *,
        ID: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ID", b"ID"]) -> None: ...

global___LeaseRevokeRequest = LeaseRevokeRequest

@typing_extensions.final
class LeaseRevokeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___ResponseHeader: ...
    def __init__(
        self,
        *,
        header: global___ResponseHeader | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["header", b"header"]) -> None: ...

global___LeaseRevokeResponse = LeaseRevokeResponse

@typing_extensions.final
class LeaseKeepAliveRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    ID: builtins.int
    """ID is the lease ID for the lease to keep alive."""
    def __init__(
        self,
        *,
        ID: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ID", b"ID"]) -> None: ...

global___LeaseKeepAliveRequest = LeaseKeepAliveRequest

@typing_extensions.final
class LeaseKeepAliveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    TTL_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___ResponseHeader: ...
    ID: builtins.int
    """ID is the lease ID from the keep alive request."""
    TTL: builtins.int
    """TTL is the new time-to-live for the lease."""
    def __init__(
        self,
        *,
        header: global___ResponseHeader | None = ...,
        ID: builtins.int = ...,
        TTL: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ID", b"ID", "TTL", b"TTL", "header", b"header"]) -> None: ...

global___LeaseKeepAliveResponse = LeaseKeepAliveResponse

@typing_extensions.final
class LeaseTimeToLiveRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    KEYS_FIELD_NUMBER: builtins.int
    ID: builtins.int
    """ID is the lease ID for the lease."""
    keys: builtins.bool
    """keys is true to query all the keys attached to this lease."""
    def __init__(
        self,
        *,
        ID: builtins.int = ...,
        keys: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ID", b"ID", "keys", b"keys"]) -> None: ...

global___LeaseTimeToLiveRequest = LeaseTimeToLiveRequest

@typing_extensions.final
class LeaseTimeToLiveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    TTL_FIELD_NUMBER: builtins.int
    GRANTEDTTL_FIELD_NUMBER: builtins.int
    KEYS_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___ResponseHeader: ...
    ID: builtins.int
    """ID is the lease ID from the keep alive request."""
    TTL: builtins.int
    """TTL is the remaining TTL in seconds for the lease; the lease will expire in
    under TTL+1 seconds.
    """
    grantedTTL: builtins.int
    """GrantedTTL is the initial granted time in seconds upon lease
    creation/renewal.
    """
    @property
    def keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """Keys is the list of keys attached to this lease."""
    def __init__(
        self,
        *,
        header: global___ResponseHeader | None = ...,
        ID: builtins.int = ...,
        TTL: builtins.int = ...,
        grantedTTL: builtins.int = ...,
        keys: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ID", b"ID", "TTL", b"TTL", "grantedTTL", b"grantedTTL", "header", b"header", "keys", b"keys"]) -> None: ...

global___LeaseTimeToLiveResponse = LeaseTimeToLiveResponse

@typing_extensions.final
class LeaseLeasesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___LeaseLeasesRequest = LeaseLeasesRequest

@typing_extensions.final
class LeaseStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    ID: builtins.int
    """TODO: int64 TTL = 2;"""
    def __init__(
        self,
        *,
        ID: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ID", b"ID"]) -> None: ...

global___LeaseStatus = LeaseStatus

@typing_extensions.final
class LeaseLeasesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    LEASES_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___ResponseHeader: ...
    @property
    def leases(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LeaseStatus]: ...
    def __init__(
        self,
        *,
        header: global___ResponseHeader | None = ...,
        leases: collections.abc.Iterable[global___LeaseStatus] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["header", b"header", "leases", b"leases"]) -> None: ...

global___LeaseLeasesResponse = LeaseLeasesResponse

@typing_extensions.final
class Member(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PEERURLS_FIELD_NUMBER: builtins.int
    CLIENTURLS_FIELD_NUMBER: builtins.int
    ISLEARNER_FIELD_NUMBER: builtins.int
    ID: builtins.int
    """ID is the member ID for this member."""
    name: builtins.str
    """name is the human-readable name of the member. If the member is not
    started, the name will be an empty string.
    """
    @property
    def peerURLs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """peerURLs is the list of URLs the member exposes to the cluster for
        communication.
        """
    @property
    def clientURLs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """clientURLs is the list of URLs the member exposes to clients for
        communication. If the member is not started, clientURLs will be empty.
        """
    isLearner: builtins.bool
    """isLearner indicates if the member is raft learner."""
    def __init__(
        self,
        *,
        ID: builtins.int = ...,
        name: builtins.str = ...,
        peerURLs: collections.abc.Iterable[builtins.str] | None = ...,
        clientURLs: collections.abc.Iterable[builtins.str] | None = ...,
        isLearner: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ID", b"ID", "clientURLs", b"clientURLs", "isLearner", b"isLearner", "name", b"name", "peerURLs", b"peerURLs"]) -> None: ...

global___Member = Member

@typing_extensions.final
class MemberListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LINEARIZABLE_FIELD_NUMBER: builtins.int
    linearizable: builtins.bool
    def __init__(
        self,
        *,
        linearizable: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["linearizable", b"linearizable"]) -> None: ...

global___MemberListRequest = MemberListRequest

@typing_extensions.final
class MemberListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    MEMBERS_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___ResponseHeader: ...
    @property
    def members(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Member]:
        """members is a list of all members associated with the cluster."""
    def __init__(
        self,
        *,
        header: global___ResponseHeader | None = ...,
        members: collections.abc.Iterable[global___Member] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["header", b"header", "members", b"members"]) -> None: ...

global___MemberListResponse = MemberListResponse
