# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lskvserver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import etcd_pb2 as etcd__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10lskvserver.proto\x12\x0clskvserverpb\x1a\netcd.proto\"\xf4\x02\n\rReceiptClaims\x12/\n\x0brequest_put\x18\x01 \x01(\x0b\x32\x18.etcdserverpb.PutRequestH\x00\x12@\n\x14request_delete_range\x18\x02 \x01(\x0b\x32 .etcdserverpb.DeleteRangeRequestH\x00\x12/\n\x0brequest_txn\x18\x03 \x01(\x0b\x32\x18.etcdserverpb.TxnRequestH\x00\x12\x31\n\x0cresponse_put\x18\x04 \x01(\x0b\x32\x19.etcdserverpb.PutResponseH\x01\x12\x42\n\x15response_delete_range\x18\x05 \x01(\x0b\x32!.etcdserverpb.DeleteRangeResponseH\x01\x12\x31\n\x0cresponse_txn\x18\x06 \x01(\x0b\x32\x19.etcdserverpb.TxnResponseH\x01\x42\t\n\x07requestB\n\n\x08response\" \n\x10SignatureReceipt\x12\x0c\n\x04leaf\x18\x01 \x01(\t\"$\n\x05Proof\x12\x0c\n\x04left\x18\x01 \x01(\t\x12\r\n\x05right\x18\x02 \x01(\t\"Z\n\x0eLeafComponents\x12\x15\n\rclaims_digest\x18\x01 \x01(\t\x12\x17\n\x0f\x63ommit_evidence\x18\x02 \x01(\t\x12\x18\n\x10write_set_digest\x18\x03 \x01(\t\"f\n\tTxReceipt\x12\x35\n\x0fleaf_components\x18\x01 \x01(\x0b\x32\x1c.lskvserverpb.LeafComponents\x12\"\n\x05proof\x18\x02 \x03(\x0b\x32\x13.lskvserverpb.Proof\"\xb9\x01\n\x07Receipt\x12\x0c\n\x04\x63\x65rt\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x0f\n\x07node_id\x18\x03 \x01(\t\x12-\n\ntx_receipt\x18\x04 \x01(\x0b\x32\x17.lskvserverpb.TxReceiptH\x00\x12;\n\x11signature_receipt\x18\x05 \x01(\x0b\x32\x1e.lskvserverpb.SignatureReceiptH\x00\x42\x10\n\x0ereceipt_extras\"8\n\x11GetReceiptRequest\x12\x10\n\x08revision\x18\x01 \x01(\x03\x12\x11\n\traft_term\x18\x02 \x01(\x04\"j\n\x12GetReceiptResponse\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.etcdserverpb.ResponseHeader\x12&\n\x07receipt\x18\x02 \x01(\x0b\x32\x15.lskvserverpb.Receiptb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lskvserver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECEIPTCLAIMS._serialized_start=47
  _RECEIPTCLAIMS._serialized_end=419
  _SIGNATURERECEIPT._serialized_start=421
  _SIGNATURERECEIPT._serialized_end=453
  _PROOF._serialized_start=455
  _PROOF._serialized_end=491
  _LEAFCOMPONENTS._serialized_start=493
  _LEAFCOMPONENTS._serialized_end=583
  _TXRECEIPT._serialized_start=585
  _TXRECEIPT._serialized_end=687
  _RECEIPT._serialized_start=690
  _RECEIPT._serialized_end=875
  _GETRECEIPTREQUEST._serialized_start=877
  _GETRECEIPTREQUEST._serialized_end=933
  _GETRECEIPTRESPONSE._serialized_start=935
  _GETRECEIPTRESPONSE._serialized_end=1041
# @@protoc_insertion_point(module_scope)
