"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the MIT License.
"""
import builtins
import collections.abc
import etcd_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ReceiptClaims(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_PUT_FIELD_NUMBER: builtins.int
    REQUEST_DELETE_RANGE_FIELD_NUMBER: builtins.int
    REQUEST_TXN_FIELD_NUMBER: builtins.int
    RESPONSE_PUT_FIELD_NUMBER: builtins.int
    RESPONSE_DELETE_RANGE_FIELD_NUMBER: builtins.int
    RESPONSE_TXN_FIELD_NUMBER: builtins.int
    @property
    def request_put(self) -> etcd_pb2.PutRequest: ...
    @property
    def request_delete_range(self) -> etcd_pb2.DeleteRangeRequest: ...
    @property
    def request_txn(self) -> etcd_pb2.TxnRequest: ...
    @property
    def response_put(self) -> etcd_pb2.PutResponse: ...
    @property
    def response_delete_range(self) -> etcd_pb2.DeleteRangeResponse: ...
    @property
    def response_txn(self) -> etcd_pb2.TxnResponse: ...
    def __init__(
        self,
        *,
        request_put: etcd_pb2.PutRequest | None = ...,
        request_delete_range: etcd_pb2.DeleteRangeRequest | None = ...,
        request_txn: etcd_pb2.TxnRequest | None = ...,
        response_put: etcd_pb2.PutResponse | None = ...,
        response_delete_range: etcd_pb2.DeleteRangeResponse | None = ...,
        response_txn: etcd_pb2.TxnResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["request", b"request", "request_delete_range", b"request_delete_range", "request_put", b"request_put", "request_txn", b"request_txn", "response", b"response", "response_delete_range", b"response_delete_range", "response_put", b"response_put", "response_txn", b"response_txn"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["request", b"request", "request_delete_range", b"request_delete_range", "request_put", b"request_put", "request_txn", b"request_txn", "response", b"response", "response_delete_range", b"response_delete_range", "response_put", b"response_put", "response_txn", b"response_txn"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["request", b"request"]) -> typing_extensions.Literal["request_put", "request_delete_range", "request_txn"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["response", b"response"]) -> typing_extensions.Literal["response_put", "response_delete_range", "response_txn"] | None: ...

global___ReceiptClaims = ReceiptClaims

@typing_extensions.final
class SignatureReceipt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEAF_FIELD_NUMBER: builtins.int
    leaf: builtins.str
    def __init__(
        self,
        *,
        leaf: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["leaf", b"leaf"]) -> None: ...

global___SignatureReceipt = SignatureReceipt

@typing_extensions.final
class Proof(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEFT_FIELD_NUMBER: builtins.int
    RIGHT_FIELD_NUMBER: builtins.int
    left: builtins.str
    right: builtins.str
    def __init__(
        self,
        *,
        left: builtins.str = ...,
        right: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["left", b"left", "right", b"right"]) -> None: ...

global___Proof = Proof

@typing_extensions.final
class LeafComponents(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLAIMS_DIGEST_FIELD_NUMBER: builtins.int
    COMMIT_EVIDENCE_FIELD_NUMBER: builtins.int
    WRITE_SET_DIGEST_FIELD_NUMBER: builtins.int
    claims_digest: builtins.str
    commit_evidence: builtins.str
    write_set_digest: builtins.str
    def __init__(
        self,
        *,
        claims_digest: builtins.str = ...,
        commit_evidence: builtins.str = ...,
        write_set_digest: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["claims_digest", b"claims_digest", "commit_evidence", b"commit_evidence", "write_set_digest", b"write_set_digest"]) -> None: ...

global___LeafComponents = LeafComponents

@typing_extensions.final
class TxReceipt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEAF_COMPONENTS_FIELD_NUMBER: builtins.int
    PROOF_FIELD_NUMBER: builtins.int
    @property
    def leaf_components(self) -> global___LeafComponents: ...
    @property
    def proof(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Proof]: ...
    def __init__(
        self,
        *,
        leaf_components: global___LeafComponents | None = ...,
        proof: collections.abc.Iterable[global___Proof] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["leaf_components", b"leaf_components"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["leaf_components", b"leaf_components", "proof", b"proof"]) -> None: ...

global___TxReceipt = TxReceipt

@typing_extensions.final
class Receipt(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CERT_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    TX_RECEIPT_FIELD_NUMBER: builtins.int
    SIGNATURE_RECEIPT_FIELD_NUMBER: builtins.int
    cert: builtins.str
    signature: builtins.bytes
    node_id: builtins.str
    @property
    def tx_receipt(self) -> global___TxReceipt: ...
    @property
    def signature_receipt(self) -> global___SignatureReceipt: ...
    def __init__(
        self,
        *,
        cert: builtins.str = ...,
        signature: builtins.bytes = ...,
        node_id: builtins.str = ...,
        tx_receipt: global___TxReceipt | None = ...,
        signature_receipt: global___SignatureReceipt | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["receipt_extras", b"receipt_extras", "signature_receipt", b"signature_receipt", "tx_receipt", b"tx_receipt"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cert", b"cert", "node_id", b"node_id", "receipt_extras", b"receipt_extras", "signature", b"signature", "signature_receipt", b"signature_receipt", "tx_receipt", b"tx_receipt"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["receipt_extras", b"receipt_extras"]) -> typing_extensions.Literal["tx_receipt", "signature_receipt"] | None: ...

global___Receipt = Receipt

@typing_extensions.final
class GetReceiptRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REVISION_FIELD_NUMBER: builtins.int
    RAFT_TERM_FIELD_NUMBER: builtins.int
    revision: builtins.int
    raft_term: builtins.int
    def __init__(
        self,
        *,
        revision: builtins.int = ...,
        raft_term: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["raft_term", b"raft_term", "revision", b"revision"]) -> None: ...

global___GetReceiptRequest = GetReceiptRequest

@typing_extensions.final
class GetReceiptResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    RECEIPT_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> etcd_pb2.ResponseHeader: ...
    @property
    def receipt(self) -> global___Receipt: ...
    def __init__(
        self,
        *,
        header: etcd_pb2.ResponseHeader | None = ...,
        receipt: global___Receipt | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header", "receipt", b"receipt"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["header", b"header", "receipt", b"receipt"]) -> None: ...

global___GetReceiptResponse = GetReceiptResponse
