FROM rust:1.72.0-slim-buster

RUN apt-get update && apt-get install -y protobuf-compiler
WORKDIR /build
COPY . .
RUN cd bencher \
    && cargo build --release \
    && cp target/release/bencher /bin/. \
    && rm -rf target
