# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
---
- hosts: all
  gather_facts: false
  tasks:
    - name: Accept new ssh fingerprints
      shell: ssh-keyscan {{ inventory_hostname }} >> ~/.ssh/known_hosts
      delegate_to: localhost

- hosts: all
  remote_user: "{{ vm_user }}"
  gather_facts: false
  tasks:
    - name: Wait for ssh to be up on the nodes
      ansible.builtin.wait_for_connection:

    - name: ping
      ping:

- hosts: all[0]
  remote_user: "{{ vm_user }}"
  gather_facts: false
  tasks:
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      community.crypto.openssh_keypair:
        path: /home/{{ vm_user }}/.ssh/id_rsa

    - name: Get pub key for the first node
      ansible.builtin.fetch:
        src: /home/{{ vm_user }}/.ssh/id_rsa.pub
        dest: bench_id_rsa.pub
        flat: true

- hosts: all
  remote_user: "{{ vm_user }}"
  gather_facts: false
  tasks:
    - name: Set authorized pub key
      authorized_key:
        state: present
        user: "{{ vm_user }}"
        key: "{{ lookup('file', 'bench_id_rsa.pub') }}"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: true

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      become: true

    - name: "Add {{vm_user}} to docker group"
      ansible.builtin.user:
        name: "{{ vm_user }}"
        group: docker
      become: true

- hosts: all[0]
  remote_user: "{{ vm_user }}"
  gather_facts: false
  tasks:
    - name: Copy lskv repo over
      ansible.posix.synchronize:
        src: "{{ playbook_dir }}/../../"
        dest: /tmp/lskv
      tags: copy

    - name: Install apt packages
      ansible.builtin.apt:
        name:
          - python3.8
          - python3.8-venv
        update_cache: true
      become: true

    - name: Install pip for sandbox
      ansible.builtin.pip:
        name: pip
        virtualenv: /tmp/lskv/.venv
        virtualenv_command: python3 -m venv

    - name: Install requirements for benchmarking
      ansible.builtin.pip:
        requirements: /tmp/lskv/requirements.txt
        virtualenv: /tmp/lskv/.venv
        virtualenv_command: python3 -m venv
      args:
        chdir: /tmp/lskv
