name: "Perf testing"

on:
  pull_request:
    branches: [main]

jobs:
  benchmark:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/ccf/app/dev:3.0.0-dev6-sgx

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Go
        run: curl -L -o go1.19.1.linux-amd64.tar.gz https://go.dev/dl/go1.19.1.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.19.1.linux-amd64.tar.gz

      - name: Build benchmark
        run: export PATH=$PATH:/usr/local/go/bin && make bin/benchmark

      - name: Get etcd
        run: make bin/etcd

      - name: Build app
        run: make build-virtual

      - name: Run benchmark
        run: export PATH=$PATH:/usr/local/go/bin && make benchmark-virtual

      - name: Plot results
        run: make execute-notebook

      - name: Mark safe directories
        run: git config --global --add safe.directory $(pwd)

      - name: set up git author
        run: |
          git config --global user.email "62645686+ccf-bot@users.noreply.github.com"
          git config --global user.name "ccf-bot"

      - name: list plots
        run: |
          git checkout -- analysis.ipynb 
          git checkout ci-plots 
          mkdir ${{ github.sha }} 
          mv plots/*.jpg ${{ github.sha }} 
          git add plots 
          git commit -m "add plots for ${{ github.sha }}"

      - name: push plots
        run: git push origin ci-plots
      
      - name: install gh cli
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: upload plots
        run: gh pr comment ${{ github.event.number }} --body "![](../blob/${{ github.sha}}/${{ github.sha }}/scatter.jpg)"
