name: "CCF KVS Perf testing"

on:
  pull_request:
    branches: [main]

jobs:
  benchmark:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/ccf/app/dev:3.0.0-dev3-sgx

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install go
        run: curl -L -o go1.19.1.linux-amd64.tar.gz https://go.dev/dl/go1.19.1.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.19.1.linux-amd64.tar.gz

      - name: Build benchmark
        run: make bin/benchmark

      - name: Get etcd
        run: make bin/etcd

      - name: Build app
        run: make build-virtual

      - name: Build app
        run: export PATH=$PATH:/usr/local/go/bin && make benchmark
