name: "Perf testing"

on:
  pull_request:
    branches: [main]

jobs:
  benchmark:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/ccf/app/dev:3.0.0-dev6-sgx

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Go
        run: curl -L -o go1.19.1.linux-amd64.tar.gz https://go.dev/dl/go1.19.1.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.19.1.linux-amd64.tar.gz

      - name: Build benchmark
        run: export PATH=$PATH:/usr/local/go/bin && make bin/benchmark

      - name: Get etcd
        run: make bin/etcd

      - name: Build app
        run: make build-virtual

      - name: Run benchmark
        run: export PATH=$PATH:/usr/local/go/bin && make benchmark-virtual

      - name: Plot results
        run: make execute-notebook

      - name: Mark safe directories
        run: git config --global --add safe.directory $(pwd)

      # - name: Checkout ci-plots
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ci-plots

      - name: list plots
        run: ls plots && mkdir ${{ github.sha }} && ls && ls plots && mv plots/*.jpg ${{ github.sha }} && ls ${{ github.sha }}

      - name: push plots
        run: git push origin ci-plots

      - name: upload plots
        run: gh pr comment ${{ github.event.number }} --body "![](../blob/${{ github.sha}}/${{ github.sha }}/scatter.jpg)"
