name: "LSKV Issue checking"

on:
  pull_request:
    branches: [main]

jobs:
  check-issues:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check issues
        run: ./scripts/check-issues.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
