name: "CCF KVS CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-app:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/ccf/app/dev:3.0.0-dev3-sgx

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build app
        run: mkdir -p build && cd build && CC="/opt/oe_lvi/clang-10" CXX="/opt/oe_lvi/clang++-10" cmake -GNinja .. && ninja

  build-docker:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/ccf/app/dev:lts-devcontainer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build container
        run: docker build -t ccf-kvs .
