name: PR Assignee

on:
  pull_request_target:
    # types:
    # - opened

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Assign PR to author
      run: |
        gh pr edit ${{ github.ref }} --add-assignee ${{ github.event.pull_request.user.login }}